apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: projectint.azurecr.io/app-frontend:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: VUE_APP_API_URL
              value: http://app-vue:80/

---
apiVersion: v1
kind: Service
metadata:
  name: app-vue
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_ProyectoIntegrador_clusterProyecto_westus
spec:
  type: LoadBalancer
  loadBalancerIP: 20.245.94.71
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80